name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: cordova
        run: npm install -g cordova

      - name: angularCli
        run: npm install -g @angular/cli
        
      - name: Ionic
        run: npm install -g @ionic/cli
      
      - name: npm
        run: npm install

      - name: Keyboard
        run: ionic cordova plugin add cordova-plugin-ionic-keyboard
        
      - name: Device
        run: ionic cordova plugin add cordova-plugin-device
        
      - name: Webview
        run: ionic cordova plugin add cordova-plugin-ionic-webview
        
      - name: statusbar
        run: ionic cordova plugin add cordova-plugin-statusbar
        
      - name: splashscreen
        run: ionic cordova plugin add cordova-plugin-splashscreen
           
      - name: file
        run: ionic cordova plugin add cordova-plugin-file
        
      - name: http
        run: ionic cordova plugin add cordova-plugin-advanced-http
        
      - name: Remove IOS platform
        run: ionic cordova platform remove ios

      - name: Add IOS platform
        run: ionic cordova platform add ios@latest

      - name: Build IOS Dev
        run: ionic cordova build ios --buildFlag="-UseModernBuildSystem=0"
        
      - name: ls
        run: cd platforms/ios && ls
